### ISSUE TITLE
 Selected language not presisting in session

### ISSUE THREAD

**Issue by Abadulrehman** [telegraf/telegraf-i18n#44]
Hi, I was following along your example code to figure out how to let the user set their language in my bot. The problem is that the bot does not seem to be saving the locale for the session. For example, on doing
`i18n.locale('ru')`
the 'greeting' message does indeed have it's language changed. However, every subsequent message after that is still in the default language. I do have `useSession `set to true, and am also doing `bot.use(Telegraf.session())`.

Am I missing something? Is there no way to make the language persist for the session?

**Comment by EdJoPaTo** [comment]
Maybe you added the i18n middleware before the session middleware?
In order to safe to the session the session has to be already existing → the session middleware has to be loaded first.

Maybe check my template as it uses both a session (not the Telegraf built in one but that doesn't matter for this) and i18n:
https://github.com/EdJoPaTo/telegram-typescript-bot-template/blob/bc033309251176d4897214b9ca6775c1a011e895/source/bot/index.ts#L27-L36

Not sure if that's the problem, but that's the first thing that came to my mind.

**Comment by Abadulrehman** [comment]
> Maybe you added the i18n middleware before the session middleware?

This was not the issue, as I confirmed that the session middleware had been added before the i18n one. However, after having a look at your code and using `telegraf-session-local` to manage the session, everything seems to be working properly now. 
Maybe it was an issue with the internal built-in Telegraf session? 

Anyways, the issue has been resolved. Thank you.
